### ISSUE TITLE
Jenkins støtte for Java 11

### ISSUE THREAD

**Issue by bgrova** [Informasjonsforvaltning/a-backend-service#67]
Dette bør gjøres i a-backend-service templaten først.

Oppdatere Jenkins byggeagenter til å støtte Java 11.

Fra Anders Elton, Computas: "Legg til ny byggetemplate som bruker et java 11 docker. Og noe logikk som gjør at Bygge jobb med java 11 starter på den templaten. Bør ikke være så vanskelig"

**Comment by KjerstiSteien** [comment]
@valosnah bruker vi fortsatt Jenkins? Eller kan jeg lukke saken?

**Comment by valosnah** [comment]
@KjerstiSteien kan lukkes
