### ISSUE TITLE
Fikse ustabilitet ved nedlasting fra Nexus

### ISSUE THREAD

**Issue by bgrova** [Informasjonsforvaltning/a-backend-service#68]
Det ser ut til å være en periodisk feil som gjør at bygg ikke klarer å laste ned artefakter fra Nexus. Hvis man kjører byggejobben på nytt, fungerer den som regel.
Den feiler ikke på samme artefakt hver gang.

Typisk feilmelding:
[ERROR] Failed to execute goal on project template-api: Could not resolve dependencies for project no.template:template-api:jar:1.0.0-SNAPSHOT: The following artifacts could not be resolved: io.springfox:springfox-swagger-ui:jar:2.9.2, com.fasterxml.jackson.core:jackson-databind:jar:2.9.9: Could not transfer artifact io.springfox:springfox-swagger-ui:jar:2.9.2 from/to nexus (http://nexus/repository/maven-group/): GET request of: io/springfox/springfox-swagger-ui/2.9.2/springfox-swagger-ui-2.9.2.jar from nexus failed: Connection reset -> [Help 1]

**Comment by KjerstiSteien** [comment]
@KurtStian er dette noe vi burde fikse, eller skal jeg lukke saken?

**Comment by KurtStian** [comment]
Kan lukkes.
